/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.UsuarioController;
import Model.Usuario;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author devmat
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botaoCadastrar = new javax.swing.JButton();
        campoNomeCadastro = new javax.swing.JTextField();
        cpfCadastro = new javax.swing.JLabel();
        campoEmailCadastro = new javax.swing.JTextField();
        campoCpfCadastro = new javax.swing.JFormattedTextField();
        campoDataCadastro = new javax.swing.JFormattedTextField();
        dataCadastro = new javax.swing.JLabel();
        cadastroNome = new javax.swing.JLabel();
        senhaCadastro = new javax.swing.JLabel();
        cadastroEmail = new javax.swing.JLabel();
        campoSenhaCadastro = new javax.swing.JPasswordField();
        imagemFundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        campoNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeCadastroActionPerformed(evt);
            }
        });
        jPanel2.add(campoNomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, -1));

        cpfCadastro.setText("CPF");
        jPanel2.add(cpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, -1));
        jPanel2.add(campoEmailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, -1));

        try {
            campoCpfCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(campoCpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, -1));

        try {
            campoDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(campoDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, -1));

        dataCadastro.setText("DATA DE NASCIMENTO");
        jPanel2.add(dataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        cadastroNome.setText("NOME");
        jPanel2.add(cadastroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        senhaCadastro.setText("SENHA");
        jPanel2.add(senhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cadastroEmail.setText("E-MAIL");
        jPanel2.add(cadastroEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        campoSenhaCadastro.setText("jPasswordField1");
        jPanel2.add(campoSenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 140, -1));

        imagemFundoCadastro.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.add(imagemFundoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
        
        try{
        UsuarioController controller = new UsuarioController();
       
        
        // configurando o formato data
        SimpleDateFormat formato = new SimpleDateFormat ("dd/MM/YYYY");
        formato.setLenient(false);
        
        // convertendo o texto do campo em um objeto java.util.Date
        java.util.Date utilDate = formato.parse(campoDataCadastro.getText());
        
        // convertendo java.util.Date para java.sql.Date
        Date sqlDate = new Date (utilDate.getTime());
        
        Usuario user = new Usuario(
                campoNomeCadastro.getText(),
                campoCpfCadastro.getText(),
                sqlDate,
                campoEmailCadastro.getText(),
                campoSenhaCadastro.getText()   
        );
        
        // chamando o metodo de cadastrar o usuario no banco de dados
        controller.cadastrandoUsuario(user);
        JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso !");
        // abra a tela de login após cadastrar
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        // fechar a tela de cadastro
        dispose();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Usuário não cadastrado !"+ e);
            
        }// fim do catch 
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void campoNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JLabel cadastroEmail;
    private javax.swing.JLabel cadastroNome;
    private javax.swing.JFormattedTextField campoCpfCadastro;
    private javax.swing.JFormattedTextField campoDataCadastro;
    private javax.swing.JTextField campoEmailCadastro;
    private javax.swing.JTextField campoNomeCadastro;
    private javax.swing.JPasswordField campoSenhaCadastro;
    private javax.swing.JLabel cpfCadastro;
    private javax.swing.JLabel dataCadastro;
    private javax.swing.JLabel imagemFundoCadastro;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel senhaCadastro;
    // End of variables declaration//GEN-END:variables
}
