/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;


import Controller.LoginController;
import Model.Usuario;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        loginEntrarCadastrar = new javax.swing.JButton();
        botaoCadastararUsuario = new javax.swing.JButton();
        imagemFundo = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\fundo.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1200));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setText("Usuário:");
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 30));

        senha.setText("Senha:");
        jPanel2.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));
        jPanel2.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, 30));

        loginEntrarCadastrar.setBackground(new java.awt.Color(102, 255, 102));
        loginEntrarCadastrar.setText("Entrar");
        loginEntrarCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEntrarCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(loginEntrarCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, 30));

        botaoCadastararUsuario.setBackground(new java.awt.Color(204, 204, 204));
        botaoCadastararUsuario.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        botaoCadastararUsuario.setText("Cadastrar usuário");
        botaoCadastararUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastararUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCadastararUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 10));

        imagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\fundo_login.jpg")); // NOI18N
        jPanel2.add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }                                      
  
    public void mudarImagem(){
   // criando um objeto da classe ImageIcon
        ImageIcon img = new ImageIcon("C:/Users/jhessikkaelly/Pictures/1.jpg");
        // adicionando uma imagem na label de imagem de fundo
        //imagemFundo.setIcon(img);
    
    }                                            

    private void loginEntrarCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEntrarCadastrarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here: // criar um objeto da classe LoginController
        LoginController controller = new LoginController();
        // criando variavel que recebe o retorno do metodo autenticar
        Usuario logou = controller.authenticate(
                campoUsuario.getText(), campoSenha.getText());
        if(logou != null){
           JOptionPane.showMessageDialog(null,"Usuário logado com sucesso! "+ logou.getNome());
           // abrir a tela Home
           TelaPrincipal telahome = new TelaPrincipal(logou);
           telahome.setVisible(true);
          // fechando a tela de Login 
          dispose();
      
        }else{
            JOptionPane.showMessageDialog(null,"Usuário e Senha Incorreta!"); 
        }// fim do else
        mudarImagem();
    }//GEN-LAST:event_loginEntrarCadastrarActionPerformed

    private void botaoCadastararUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastararUsuarioActionPerformed
        // TODO add your handling code here:
        // chamando tela de de cadastro
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);
        // fechar a tela de login
        dispose();
    }//GEN-LAST:event_botaoCadastararUsuarioActionPerformed

         
        
    // fim do mudarImagem
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastararUsuario;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginEntrarCadastrar;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
