/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;
import Model.Usuario;
import java.io.File;
import java.io.InputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

import javax.swing.SwingUtilities;
import javax.sound.sampled.AudioFileFormat.*;



/**
 *
 * @author devmat
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaPrincipal(Usuario user) {
        initComponents();
        usuarioHome.setText(user.getNome());
        som();
    }
    public void som() {
    try {
        // Caminho absoluto do arquivo de áudio (certifique-se de que o arquivo está nesse local)
        String resource = "C:/Users/devmat/Downloads/That_s-the-One-Ryan-McCaffrey_Go-By-Ocean.wav";

        // Carrega o arquivo de áudio
        File audioFile = new File(resource);
        AudioInputStream audioInput = AudioSystem.getAudioInputStream(audioFile);

        // Inicializa o Clip para reprodução
        Clip oClip = AudioSystem.getClip();
        oClip.open(audioInput);

        // Toca o áudio uma vez
        oClip.loop(0);

        // Opcional: pode usar o LOOP_CONTINUOUSLY para repetir
        // oClip.loop(Clip.LOOP_CONTINUOUSLY);

        oClip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
    
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        usuarioInferior = new javax.swing.JLabel();
        botaoCompras = new javax.swing.JButton();
        botaoProdutos = new javax.swing.JButton();
        botaoCarrinho = new javax.swing.JButton();
        botaoPerfil = new javax.swing.JButton();
        iconePesquisa = new javax.swing.JLabel();
        campoPesquisa = new javax.swing.JTextField();
        usuarioHome = new javax.swing.JTextField();
        imagemFundoHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioInferior.setBackground(new java.awt.Color(255, 255, 255));
        usuarioInferior.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        usuarioInferior.setText("Suel Ribeiro");
        home.add(usuarioInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 100, 20));

        botaoCompras.setBackground(new java.awt.Color(204, 255, 255));
        botaoCompras.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\icons8-banknotes-26.png")); // NOI18N
        botaoCompras.setText("Compras");
        home.add(botaoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 130, 50));

        botaoProdutos.setBackground(new java.awt.Color(204, 255, 255));
        botaoProdutos.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\icons8-produtos-30.png")); // NOI18N
        botaoProdutos.setText("Produtos");
        home.add(botaoProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, 50));

        botaoCarrinho.setBackground(new java.awt.Color(204, 255, 255));
        botaoCarrinho.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\icons8-carrinho-de-compras-24.png")); // NOI18N
        botaoCarrinho.setText("Carrinho");
        home.add(botaoCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 120, 50));

        botaoPerfil.setBackground(new java.awt.Color(204, 255, 255));
        botaoPerfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\icons8-user-24.png")); // NOI18N
        botaoPerfil.setText("Perfil");
        botaoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPerfilActionPerformed(evt);
            }
        });
        home.add(botaoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, 50));

        iconePesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\icons8-pesquisa-24.png")); // NOI18N
        home.add(iconePesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 50, 40));
        home.add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 42, 330, 60));

        usuarioHome.setBackground(new java.awt.Color(0, 204, 204));
        usuarioHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarioHome.setText("SUEL RIBEIRO");
        usuarioHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioHomeActionPerformed(evt);
            }
        });
        home.add(usuarioHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        imagemFundoHome.setBackground(new java.awt.Color(204, 255, 255));
        imagemFundoHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\imagem desfocada de shopping.jpg")); // NOI18N
        imagemFundoHome.setText("Perfil");
        home.add(imagemFundoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPerfilActionPerformed

    private void usuarioHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            Usuario user = null;
                new TelaPrincipal(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCarrinho;
    private javax.swing.JButton botaoCompras;
    private javax.swing.JButton botaoPerfil;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JPanel home;
    private javax.swing.JLabel iconePesquisa;
    private javax.swing.JLabel imagemFundoHome;
    private javax.swing.JTextField usuarioHome;
    private javax.swing.JLabel usuarioInferior;
    // End of variables declaration//GEN-END:variables
}
